### ISSUE TITLE
Next steps - tracking migration away from python 3.8 

### ISSUE THREAD

**Issue by lwasser** [stravalib/stravalib#417]
this is a temporary issue to track the next steps of our release cycle
We are going to drop python 3.8. The next steps towards that are:

- [x] @lwasser creates 1.4 release with what's been merged on main.
- [x] we review and approve #416 
- [x] @enadeau rebases #415  and we review /merge
- [ ] we create a 1.5 release with the newly dropped python 3.8 implementation 

After that i'll work a bit more on the nox migration (moving stravalib to a src/ layout and adding a nox build session) and updating docs with NEP-29 / python version support details (and then we can close https://github.com/stravalib/stravalib/issues/254 as well! 🎉 (this is not a checklist so this tracking issue can get closed quickly!)

**Comment by enadeau** [comment]
Make sense I'm on board with that!

**Comment by lwasser** [comment]
excellent. the release is building now - should be on pypi shortly!

**Comment by lwasser** [comment]
✅ [stravalib 1.4 is on pypi now!](https://pypi.org/project/stravalib/) 🎉

**Comment by lwasser** [comment]
excellent - we are now ready to rebase #415 and then it can be approved and merged. then we can  merge #397  and implement a release.

**Comment by lwasser** [comment]
Ok - i *think* we are ready for a new release version 1.5. @enadeau do you want to try to implement the release or would you like me to? i don't mind either way but if you want to learn our release process i'm happy to help! 

if you'd rather not at this time, i can just do it!

**Comment by enadeau** [comment]
Maybe I could give it a try over the weekend.

I'm wondering if there's any ohter issue we should try to put in the release. Maybe #400 ?

**Comment by lwasser** [comment]
@enadeau i think for this release we should stick to the plan and just create a 1.5 release now. there are a handful of other pydantic related deprecations / refactoring tasks that i think would warrant another minor / major (2.0 release) plan . i do want to pull @jsamoocha into this but it might be good to come up with an incremental plan that moves us towards 2.0 support / cleanup of backwards - compatibility elements. 

in the meantime, let's implement this 1.5 that drops 3.8!! 🚀

**Comment by enadeau** [comment]
Okay great I'll try to do the release this weekend and ask you if I need help. Than it would be nice to have a discussion about how we want to move forward
